name = "cloudflare-docker-proxy"
main = "src/index.js"
compatibility_date = "2023-12-01"

# 部署到 Workers （无需 Pages）
workers_dev = false

# 自定义域名（Cloudflare 中绑定 docker.huaqingxu.dpdns.org）
routes = [
   { pattern = "docker.huaqingxu.dpdns.org", custom_domain = true },
   { pattern = "quay.huaqingxu.dpdns.org", custom_domain = true },
   { pattern = "gcr.huaqingxu.dpdns.org", custom_domain = true },
   { pattern = "k8s-gcr.huaqingxu.dpdns.org", custom_domain = true },
   { pattern = "k8s.huaqingxu.dpdns.org", custom_domain = true },
   { pattern = "ghcr.huaqingxu.dpdns.org", custom_domain = true },
   { pattern = "cloudsmith.huaqingxu.dpdns.org", custom_domain = true },
]

[assets]
directory = "./dist"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[vars]
CUSTOM_DOMAIN = "huaqingxu.dpdns.org"
DEFAULT_UPSTREAM = "https://mirror.gcr.io"
ALLOW_DIRECT = "true"
CACHE_TTL = "3600"

[env.vars]
CUSTOM_DOMAIN = "huaqingxu.dpdns.org"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "huaqingxu.dpdns.org"

[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.libcuda.so", custom_domain = true },
#   { pattern = "quay.libcuda.so", custom_domain = true },
#   { pattern = "gcr.libcuda.so", custom_domain = true },
#   { pattern = "k8s-gcr.libcuda.so", custom_domain = true },
#   { pattern = "k8s.libcuda.so", custom_domain = true },
#   { pattern = "ghcr.libcuda.so", custom_domain = true },
#   { pattern = "cloudsmith.libcuda.so", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
